name: CI/CD Pipeline - Dev Website

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug Current Directory
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -a

      - name: Build and Push Docker Image
        run: |
          docker build -t madhesh1171/dev:latest .
          docker push madhesh1171/dev:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./iac
        run: terraform init

      - name: Apply Terraform
        working-directory: ./iac
        env:
          TF_VAR_docker_image: madhesh1171/dev:latest
        run: terraform apply -auto-approve -lock=false
