steps:
  # Step 1: Checkout repository
  - name: Checkout Repository
    uses: actions/checkout@v4

  # Step 2: Set up Docker
  - name: Set up Docker
    uses: docker/setup-buildx-action@v3

  # Step 3: Login to Docker Hub
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  # Step 4: Build and Push Docker Image
  - name: Build and Push Docker Image
    run: |
      docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dev:latest .
      docker push ${{ secrets.DOCKERHUB_USERNAME }}/dev:latest

  # Step 5: Setup Terraform
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: 1.9.0

  # Step 6: Initialize Terraform
  - name: Initialize Terraform
    working-directory: ./iac
    run: terraform init

  # Step 7: Apply Terraform (Deploy to Minikube/Kubernetes)
  - name: Apply Terraform
    working-directory: ./iac
    env:
      TF_VAR_docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/dev:latest
    run: terraform apply -auto-approve -lock=false
