name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 3. Build Docker image
      - name: Build Docker image
        run: docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/dev:${{ github.sha }} .

      # 4. Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/dev:${{ github.sha }}

      # 5. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      # 6. Terraform Init
      - name: Terraform Init
        working-directory: ./iac
        run: terraform init

      # 7. Terraform Apply
      - name: Terraform Apply
        working-directory: ./iac
        env:
          TF_VAR_docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/dev:${{ github.sha }}
        run: terraform apply -auto-approve -input=false
